import { useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { supabase } from '../lib/supabase'

const TABS = [
  { id: 'dashboard', label: 'Dashboard', path: '/j1' },
  { id: 'expenses',  label: 'Expenses',  path: '/j2' },
  { id: 'documents', label: 'Documents', path: '/j3' },
  { id: 'coach',     label: 'AI Coach',  path: '/j4' },
  { id: 'directory', label: 'Directory', path: '/j5' },
  { id: 'essentials',label: 'Essentials',path: '/j6' },
  { id: 'resources', label: 'Resources', path: '/resources' },
]

const FILTERS = ['All', 'Attorneys', 'RCICs', 'CPAs', 'Financial Advisors', 'Real Estate', 'MLO / Mortgage', 'Healthcare', 'Vehicle Import', 'Business Brokers']

const PROFESSIONALS = [
  {
    id: 1,
    name: 'Mena Maimone',
    title: 'Immigration Attorney',
    firm: 'Maimone Legal',
    location: 'Fort Lauderdale, FL',
    address: '550 W Cypress Creek Rd, Suite 370\nFort Lauderdale, FL 33309',
    phones: [
      { label: 'Florida', number: '(888) 863-3207' },
      { label: 'Texas',   number: '(888) 370-6695' },
    ],
    hours: 'Monday – Friday, 9am – 5pm',
    specialties: ['EB-5', 'E-2', 'L-1', 'TN'],
    languages: ['English', 'French'],
    canadian: 'Extensive experience',
    bio: 'Canadian-born immigration attorney. Founder of the Canadians Moving to Florida and USA community (80,000+ members). Has personally navigated the same journey her clients are on.',
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: 5,
    reviews: null,
    expanded: true,
    primaryAction: 'Request Introduction',
    has_account: true,
    supabase_id: '63604efe-b9bd-4e6e-b2c4-b5a1b09c1cbc',
  },
  {
    id: 2,
    name: 'James R. Patterson',
    title: 'Immigration Attorney',
    firm: 'Patterson Immigration Law',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['E-2', 'TN', 'H-1B'],
    languages: ['English', 'Spanish'],
    canadian: null,
    bio: 'Specializes in business and investor visas for entrepreneurs entering the US market. 15 years experience.',
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: 4,
    reviews: 23,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 3,
    name: 'Sarah Chen',
    title: 'Senior Immigration Attorney',
    firm: 'Global Mobility Partners',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['EB-5', 'L-1', 'EB-1'],
    languages: ['English', 'Mandarin'],
    canadian: null,
    bio: 'Dedicated to helping high-net-worth individuals and families achieve permanent US residency through investor pathways.',
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: 4,
    reviews: 31,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 4,
    name: 'David MacKenzie CPA',
    title: 'Cross-Border Tax Specialist',
    firm: 'MacKenzie Cross-Border Advisors',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['CRA departure', 'US filing', 'FBAR', 'RRSP treatment', 'FATCA compliance'],
    languages: null,
    canadian: 'Extensive',
    bio: 'Canadian-trained CPA now based in Tampa. Specializes exclusively in Canada-US cross-border tax situations.',
    note: null,
    badge: null,
    category: 'CPAs',
    stars: 5,
    reviews: 18,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 12,
    name: 'Jennifer Walsh CPA CA',
    title: 'International Tax Advisor',
    firm: 'Walsh and Associates',
    location: 'Fort Lauderdale, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Departure returns', 'Deemed disposition', 'Rental withholding'],
    languages: null,
    canadian: null,
    bio: 'Former CRA auditor. Now helps Canadians navigate the departure process and establish clean US tax profiles.',
    note: null,
    badge: null,
    category: 'CPAs',
    stars: 4,
    reviews: 14,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 5,
    name: 'Robert Sandoval',
    title: 'Certified Business Broker',
    firm: 'Florida Business Exchange',
    location: 'Southwest Florida',
    address: null,
    phones: [],
    hours: null,
    specialties: ['E-2 qualifying businesses', 'Franchise resales', 'Service businesses'],
    languages: null,
    canadian: null,
    bio: 'Specializes in identifying and valuing businesses that qualify for E-2 investor visa requirements.',
    note: null,
    badge: null,
    category: 'Business Brokers',
    stars: 4,
    reviews: 14,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 13,
    name: 'Amanda Foster',
    title: 'M&A Advisor',
    firm: 'Foster Business Advisors',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Business valuations', 'E-2 compliance', 'Acquisition due diligence'],
    languages: null,
    canadian: null,
    bio: 'Former immigration paralegal turned business broker. Understands exactly what USCIS looks for in an E-2 qualifying business.',
    note: null,
    badge: null,
    category: 'Business Brokers',
    stars: 5,
    reviews: 9,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 14,
    name: 'Michael Torres',
    title: 'Commercial Real Estate Specialist',
    firm: 'LQ Commercial',
    location: 'Sarasota & Punta Gorda, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Canadian buyers', 'E-2 qualifying businesses', 'Investment properties'],
    languages: null,
    canadian: null,
    bio: 'Specializes in helping Canadian investors find E-2 qualifying businesses and investment properties in Southwest FL.',
    note: null,
    badge: null,
    category: 'Real Estate',
    stars: 4,
    reviews: 31,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 15,
    name: 'Linda Beaumont',
    title: 'Residential Specialist',
    firm: 'Premier Properties',
    location: 'Tampa Bay, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Foreign national buyers', 'Canadian purchasers', 'Relocation'],
    languages: null,
    canadian: null,
    bio: 'Helps Canadian and international buyers navigate the Florida residential market with no US credit history required.',
    note: null,
    badge: null,
    category: 'Real Estate',
    stars: 4,
    reviews: 19,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 6,
    name: 'RCIC Name',
    title: 'Regulated Canadian Immigration Consultant',
    firm: 'Firm Name — City, Canada',
    location: 'Canada',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Pre-departure planning', 'US visa referrals', 'Canadian exit strategy'],
    languages: null,
    canadian: null,
    bio: null,
    note: 'RCICs are regulated by CICC and can advise on Canadian immigration matters. For US visa applications, they work alongside US-licensed attorneys.',
    badge: null,
    category: 'RCICs',
    stars: 4,
    reviews: 12,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 7,
    name: 'Advisor Name',
    title: 'Cross-Border Financial Advisor',
    firm: 'Firm Name — City, FL',
    location: null,
    address: null,
    phones: [],
    hours: null,
    specialties: ['RRSP/TFSA wind-down', 'US portfolio setup', 'Cross-border tax planning', 'Retirement accounts'],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Financial Advisors',
    stars: 5,
    reviews: 9,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 8,
    name: 'Carlos Rivera',
    title: 'Mortgage Loan Officer',
    firm: 'CrossBorder Lending Group',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: ['Foreign national mortgages', 'ITIN loans', 'DSCR investment loans', 'Canadian buyers'],
    languages: null,
    canadian: null,
    bio: 'Specializes in mortgage solutions for Canadians and foreign nationals purchasing in Florida without US credit.',
    note: null,
    badge: null,
    category: 'MLO / Mortgage',
    stars: 4,
    reviews: 22,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 9,
    name: 'Doctor Name, MD',
    title: 'Primary Care Physician',
    firm: 'Practice Name — Tampa, FL',
    location: null,
    address: null,
    phones: [],
    hours: null,
    specialties: ['New arrivals', 'Foreign medical records', 'Insurance transitions'],
    languages: null,
    canadian: null,
    bio: null,
    note: 'Experienced with new arrivals — understands foreign medical records and insurance transitions',
    accepting: true,
    badge: null,
    category: 'Healthcare',
    stars: 5,
    reviews: 24,
    expanded: false,
    primaryAction: 'Book appointment',
    has_account: false,
  },
  {
    id: 10,
    name: 'Dentist Name, DDS',
    title: 'General Dentist',
    firm: 'Practice Name — Tampa, FL',
    location: null,
    address: null,
    phones: [],
    hours: null,
    specialties: ['General dentistry', 'New patients welcome'],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    accepting: true,
    badge: null,
    category: 'Healthcare',
    stars: 4,
    reviews: 19,
    expanded: false,
    primaryAction: 'Book appointment',
    has_account: false,
  },
  {
    id: 11,
    name: 'Company Name',
    title: 'Vehicle Import Specialist',
    firm: 'City, FL',
    location: null,
    address: null,
    phones: [],
    hours: null,
    specialties: ['Canadian vehicle imports', 'RIV registration', 'US compliance modifications', 'Customs'],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Vehicle Import',
    stars: 4,
    reviews: 14,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 16,
    name: 'Luciano Barcellos',
    title: 'Immigration Attorney',
    firm: 'Barcellos Law',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 17,
    name: 'Carmen Arce',
    title: 'Immigration Attorney',
    firm: 'Arce Immigration Law',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 18,
    name: 'Jose E. Latour',
    title: 'Immigration Attorney',
    firm: 'LatourLaw P.A.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 19,
    name: 'Katerina I Barquet Stege',
    title: 'Immigration Attorney',
    firm: 'Barquet Stege PLLC',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 20,
    name: 'Sandy Pineda',
    title: 'Immigration Attorney',
    firm: 'SRP Law',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 21,
    name: 'Yunior Pineiro',
    title: 'Immigration Attorney',
    firm: 'Pineiro Law',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 22,
    name: 'Georgia Brown Gillett',
    title: 'Immigration Attorney',
    firm: 'The Gillett Law Firm P.A.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 23,
    name: 'Brian Chase Malone',
    title: 'Immigration Attorney',
    firm: 'Brian Chase Malone Esq.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 24,
    name: 'Jacob Lawrence Ratzan',
    title: 'Immigration Attorney',
    firm: 'Jacob L. Ratzan P.A.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 25,
    name: 'Kari Ann Fonte',
    title: 'Immigration Attorney',
    firm: 'Fonte Immigration Firm P.L.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 26,
    name: 'Ekaterina Mouratova',
    title: 'Immigration Attorney',
    firm: 'Immigration Center of Ekaterina Mouratova PA',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 27,
    name: 'Jorge Rivera',
    title: 'Immigration Attorney',
    firm: 'Immigration Group LLC',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 28,
    name: 'Erwin Diaz-Solis',
    title: 'Immigration Attorney',
    firm: 'Law Offices of Erwin Diaz-Solis P.A.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 29,
    name: 'Michael A. Harris',
    title: 'Immigration Attorney',
    firm: 'HarrisLaw P.A.',
    location: 'Miami, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 30,
    name: 'Connie Kaplan',
    title: 'Immigration Attorney',
    firm: 'Connie Kaplan',
    location: 'Fort Lauderdale, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 31,
    name: 'Shilpa Grover Malik',
    title: 'Immigration Attorney',
    firm: 'VisaNation Law Group PLLC',
    location: 'Fort Lauderdale, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 32,
    name: 'Robert Albert Pascal',
    title: 'Immigration Attorney',
    firm: 'Robert A. Pascal P.A.',
    location: 'Fort Lauderdale, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 33,
    name: 'William Gerstein',
    title: 'Immigration Attorney',
    firm: 'Gerstein & Gerstein Attorneys P.A.',
    location: 'Fort Lauderdale, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 34,
    name: 'Kevin Daniel Slattery',
    title: 'Immigration Attorney',
    firm: 'Kevin D. Slattery PA',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 35,
    name: 'Kathryn E. Reeves',
    title: 'Immigration Attorney',
    firm: 'Immigration Attorneys LLP',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 36,
    name: 'April A. Caminez Bentley',
    title: 'Immigration Attorney',
    firm: 'Adams and Reese LLP',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 37,
    name: 'Vitalia D Shafer',
    title: 'Immigration Attorney',
    firm: 'Diaz Shafer P.A.',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 38,
    name: 'Maria del Carmen Ramos',
    title: 'Immigration Attorney',
    firm: 'Shumaker Loop & Kendrick LLP',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 39,
    name: 'Miguel Angel Mora Jr.',
    title: 'Immigration Attorney',
    firm: 'Mora Immigration Group Tampa',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 40,
    name: 'Christian G.A. Zeller',
    title: 'Immigration Attorney',
    firm: 'Maney Gordon Zeller P.A.',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 41,
    name: 'Andrea G. Kahn',
    title: 'Immigration Attorney',
    firm: 'Kahn Immigration Law',
    location: 'Tampa, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 42,
    name: 'Luciane F M Tavares',
    title: 'Immigration Attorney',
    firm: 'American Immigration Associates LLC',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 43,
    name: 'Elana Jean Laverty',
    title: 'Immigration Attorney',
    firm: 'BTL Immigration',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 44,
    name: 'Richard Henry Maney',
    title: 'Immigration Attorney',
    firm: 'Maney Gordon Zeller P.A.',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 45,
    name: 'Natalia Gove',
    title: 'Immigration Attorney',
    firm: 'GrayRobinson PA',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 46,
    name: 'Natalie D. Hall',
    title: 'Immigration Attorney',
    firm: 'The Law Office of Natalie D. Hall P.A.',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 47,
    name: 'Carlos M. Colombo',
    title: 'Immigration Attorney',
    firm: 'Colombo & Hurd PL',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 48,
    name: 'Joseph ThurdeKoos',
    title: 'Immigration Attorney',
    firm: 'Joseph ThurdeKoos Esq.',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 49,
    name: 'Francisco Symphorien-Saavedra',
    title: 'Immigration Attorney',
    firm: 'Symphorien-Saavedra Law P.A.',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 50,
    name: 'Kashmira I. Bhavsar',
    title: 'Immigration Attorney',
    firm: 'Bhavsar Law Group P.A.',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 51,
    name: 'Chad M. Brandt',
    title: 'Immigration Attorney',
    firm: 'The Law Office of Chad M. Brandt PA',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 52,
    name: 'Andre Linhares',
    title: 'Immigration Attorney',
    firm: 'Linhares Law',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 53,
    name: 'Amit Dehra',
    title: 'Immigration Attorney',
    firm: 'Dehra Miotke LLC',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  {
    id: 54,
    name: 'Walter G Santos',
    title: 'Immigration Attorney',
    firm: 'Santos Law Firm PL',
    location: 'Orlando, FL',
    address: null,
    phones: [],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
  },
  // ── Florida (additional) ─────────────────────────────────────────────────────
  {
    id: 55,
    name: 'Luciano Barcellos',
    title: 'Immigration Attorney',
    firm: 'Barcellos Law',
    location: 'Miami, FL',
    address: '1000 Brickell Ave Ste 1100, Miami, FL 33131',
    phones: [{ label: 'Office', number: '786-354-5822' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@barcellos.law',
  },
  {
    id: 56,
    name: 'Carmen Arce',
    title: 'Immigration Attorney',
    firm: 'Arce Immigration Law',
    location: 'Miami, FL',
    address: '3692 SW 24th St, Miami, FL 33145',
    phones: [{ label: 'Office', number: '305-330-6262' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@arceglobal.com',
  },
  {
    id: 57,
    name: 'Connie Kaplan',
    title: 'Immigration Attorney',
    firm: 'Law Offices of Connie Kaplan, P.A.',
    location: 'Fort Lauderdale, FL',
    address: '110 SE 6th St #1736, Fort Lauderdale, FL 33301',
    phones: [{ label: 'Office', number: '754-757-2447' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 58,
    name: 'Shilpa Grover Malik',
    title: 'Immigration Attorney',
    firm: 'VisaNation Law Group PLLC',
    location: 'Fort Lauderdale, FL',
    address: '800 Corporate Drive Ste 206, Fort Lauderdale, FL 33334',
    phones: [{ label: 'Office', number: '954-604-6406' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@immi-usa.com',
  },
  {
    id: 59,
    name: 'Kevin Daniel Slattery',
    title: 'Immigration Attorney',
    firm: 'Kevin D. Slattery, P.A.',
    location: 'Tampa, FL',
    address: '4860 W Gandy Blvd, Tampa, FL 33611',
    phones: [{ label: 'Office', number: '813-839-7474' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@slattery-law.com',
  },
  {
    id: 60,
    name: 'Kathryn E. Reeves',
    title: 'Immigration Attorney',
    firm: 'Immigration Attorneys, LLP',
    location: 'Tampa, FL',
    address: '2102 W. Cleveland St., Tampa, FL 33606',
    phones: [{ label: 'Office', number: '813-463-0020' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'kreeves@immattyllp.com',
  },
  {
    id: 61,
    name: 'Luciane F M Tavares',
    title: 'Immigration Attorney',
    firm: 'American Immigration Associates LLC',
    location: 'Orlando, FL',
    address: '300 S Orange Ave Suite 1150, Orlando, FL 32801',
    phones: [{ label: 'Office', number: '407-901-7556' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 62,
    name: 'Elana Jean Laverty',
    title: 'Immigration Attorney',
    firm: 'BTL Immigration',
    location: 'Orlando, FL',
    address: null,
    phones: [{ label: 'Office', number: '407-489-2645' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'elaverty@btlimmigration.com',
  },
  // ── Texas ────────────────────────────────────────────────────────────────────
  {
    id: 63,
    name: 'Lance Curtright',
    title: 'Immigration Attorney',
    firm: 'De Mott, Curtright, & Armendariz (DMCA)',
    location: 'Houston, TX',
    address: '601 Sawyer Suite 280, Houston, TX 77007',
    phones: [{ label: 'Office', number: '713-373-3765' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'lance@dmcausa.com',
  },
  {
    id: 64,
    name: 'Virginia Shevaun Jijon-Caamano',
    title: 'Immigration Attorney',
    firm: 'Jackson, Landrith & Kulesz, PC',
    location: 'Arlington, TX',
    address: '601 W Abram Street, Arlington, TX 76010',
    phones: [{ label: 'Office', number: '817-226-1100' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'contact@jlkattorneys.com',
  },
  {
    id: 65,
    name: 'Faye M. Kolly',
    title: 'Immigration Attorney',
    firm: 'McChesney Kolly PLLC',
    location: 'Austin, TX',
    address: '901 Mopac Expressway South Ste. 300, Austin, TX 78746',
    phones: [{ label: 'Office', number: '512-643-2941' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 66,
    name: 'Alfredo Lozano',
    title: 'Immigration Attorney',
    firm: 'The Lozano Law Firm, PLLC',
    location: 'San Antonio, TX',
    address: '5718 University Heights Blvd. Suite 104, San Antonio, TX 78249',
    phones: [{ label: 'Office', number: '210-899-2290' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 67,
    name: 'Maria McIntyre',
    title: 'Immigration Attorney',
    firm: 'Nayar & McIntyre, LLP',
    location: 'Irving, TX',
    address: '800 W Airport Freeway Suite 1100, Irving, TX 75062',
    phones: [{ label: 'Office', number: '972-445-4114' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@dfw-immigration.com',
  },
  {
    id: 68,
    name: 'Lonnie Hank Robin',
    title: 'Immigration Attorney',
    firm: 'Law Office of Lonnie Hank Robin',
    location: 'Fort Worth, TX',
    address: 'PO Box 17400, Fort Worth, TX 76102',
    phones: [{ label: 'Office', number: '817-870-1450' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'lonnie@lonnierobin.com',
  },
  {
    id: 69,
    name: 'Kelley Noemy Ortega',
    title: 'Immigration Attorney',
    firm: 'Jaime Barron PC',
    location: 'Dallas, TX',
    address: '7610 N Stemmons Fwy Suite 555, Dallas, TX 75247',
    phones: [{ label: 'Office', number: '214-267-9300' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@jaimebarron.com',
  },
  {
    id: 70,
    name: 'Debra Rodriguez',
    title: 'Immigration Attorney',
    firm: 'Debra Rodriguez, P.C.',
    location: 'Corpus Christi, TX',
    address: '713 Ayers Street, Corpus Christi, TX 78404',
    phones: [{ label: 'Office', number: '361-883-8900' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@debrarodriguez.com',
  },
  // ── North Carolina ───────────────────────────────────────────────────────────
  {
    id: 71,
    name: 'H. Glenn Fogle Jr.',
    title: 'Immigration Attorney',
    firm: 'The Fogle Law Firm, LLC',
    location: 'Charlotte, NC',
    address: '301 S. McDowell Street Suite 800, Charlotte, NC 28204',
    phones: [{ label: 'Office', number: '704-405-9060' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@foglelaw.com',
  },
  {
    id: 72,
    name: 'Mary Lynn Anna Tedesco',
    title: 'Immigration Attorney',
    firm: 'Tedesco Legal, PC',
    location: 'Charlotte, NC',
    address: 'PO Box 242066, Charlotte, NC 28227',
    phones: [{ label: 'Office', number: '980-999-1253' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 73,
    name: 'Patrick Hatch',
    title: 'Immigration Attorney',
    firm: 'Hatch Rockers Immigration',
    location: 'Raleigh, NC',
    address: '4909 Waters Edge Drive Suite 218, Raleigh, NC 27606',
    phones: [{ label: 'Office', number: '919-688-1788' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@hatchrockers.com',
  },
  {
    id: 74,
    name: 'Robb Hill',
    title: 'Immigration Attorney',
    firm: 'Robb Hill, Attorney at Law, PLLC',
    location: 'Asheville, NC',
    address: '35 Orange Street, Asheville, NC 28801',
    phones: [{ label: 'Office', number: '828-210-8171' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 75,
    name: 'Jeffrey Bruce Widdison',
    title: 'Immigration Attorney',
    firm: 'McKinney Immigration Law',
    location: 'Wilmington, NC',
    address: '720 N 3rd Street Ste 102, Wilmington, NC 28401',
    phones: [{ label: 'Office', number: '336-275-5885' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 76,
    name: 'David J. Long',
    title: 'Immigration Attorney',
    firm: 'Long & Chang LLP',
    location: 'Jamestown, NC',
    address: '4915 Piedmont Parkway Suite 103, Jamestown, NC 27282',
    phones: [{ label: 'Office', number: '336-855-5700' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@longchangonline.com',
  },
  {
    id: 77,
    name: 'Daniel Christmann',
    title: 'Immigration Attorney',
    firm: 'Christmann Legal Immigration Law',
    location: 'Greensboro, NC',
    address: '7800 Airport Center Drive Suite 401, Greensboro, NC 27409',
    phones: [{ label: 'Office', number: '336-790-2101' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@christmannlegal.com',
  },
  {
    id: 78,
    name: 'Stephen H. Smalley',
    title: 'Immigration Attorney',
    firm: 'Ogletree, Deakins, Nash et al.',
    location: 'Raleigh, NC',
    address: '4208 Six Forks Road Suite 1100, Raleigh, NC 27609',
    phones: [{ label: 'Office', number: '919-787-9700' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'stephen.smalley@ogletree.com',
  },
  // ── South Carolina ───────────────────────────────────────────────────────────
  {
    id: 79,
    name: 'Kristen Ness Ayers',
    title: 'Immigration Attorney',
    firm: 'Ayers Immigration Law Firm',
    location: 'Charleston, SC',
    address: '1466 Wando Landing Street, Charleston, SC 29492',
    phones: [{ label: 'Office', number: '678-528-3196' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 80,
    name: 'Jean Sterling Chillico',
    title: 'Immigration Attorney',
    firm: 'Chillico & Associates, LLC',
    location: 'Mount Pleasant, SC',
    address: '3850 Bessemer Rd. Suite 120, Mount Pleasant, SC 29466',
    phones: [{ label: 'Office', number: '843-779-2112' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'admin@chillico.law',
  },
  {
    id: 81,
    name: 'Lawrence J. Needle',
    title: 'Immigration Attorney',
    firm: 'Lawrence J. Needle, P.A.',
    location: 'Columbia, SC',
    address: '339 Heyward St., Columbia, SC 29201',
    phones: [{ label: 'Office', number: '803-376-1203' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 82,
    name: 'Aimee E. Deverall',
    title: 'Immigration Attorney',
    firm: 'Deverall Immigration Law, LLC',
    location: 'Bluffton, SC',
    address: '10 Pinckney Colony Road Suite 102, Bluffton, SC 29909',
    phones: [{ label: 'Office', number: '843-815-7444' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@deverall-law.com',
  },
  {
    id: 83,
    name: 'Laura E. Martin',
    title: 'Immigration Attorney',
    firm: 'Martin & Martin PA',
    location: 'Greenville, SC',
    address: '1415 Augusta St, Greenville, SC 29605',
    phones: [{ label: 'Office', number: '864-271-1822' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'laura@martinslawfirm.com',
  },
  {
    id: 84,
    name: 'Mariana Toledo-Hermina',
    title: 'Immigration Attorney',
    firm: 'Law Office of Mariana Toledo-Hermina',
    location: 'Fort Mill, SC',
    address: '120 Academy St, Fort Mill, SC 29715',
    phones: [{ label: 'Office', number: '980-785-4923' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 85,
    name: 'Garrett D. Steck',
    title: 'Immigration Attorney',
    firm: 'Haynsworth Sinkler Boyd PA',
    location: 'Greenville, SC',
    address: '1 North Main Street Suite 200, Greenville, SC 29601',
    phones: [{ label: 'Office', number: '(864) 240-3200' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'gsteck@hsblawfirm.com',
  },
  {
    id: 86,
    name: 'Jessica Lynn Wallace',
    title: 'Immigration Attorney',
    firm: 'Wallace Immigration Law, LLC',
    location: 'Greer, SC',
    address: '22 Parkway Commons Way, Greer, SC 29650',
    phones: [{ label: 'Office', number: '864-326-4833' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'jessica@wallace-law.com',
  },
  // ── Georgia ──────────────────────────────────────────────────────────────────
  {
    id: 87,
    name: 'Renata C Lillywhite',
    title: 'Immigration Attorney',
    firm: 'Alliance Immigration Law LLC',
    location: 'Marietta, GA',
    address: '4343 Shallowford Rd Suite 121, Marietta, GA 30062',
    phones: [{ label: 'Office', number: '678-528-3196' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 88,
    name: 'Sasha N Westerman-Keuning',
    title: 'Immigration Attorney',
    firm: 'Rostova Westerman Law Group',
    location: 'Clayton, GA',
    address: '172 N Main St Suite 1, Clayton, GA 30525',
    phones: [{ label: 'Office', number: '786-442-3177' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 89,
    name: 'Layli Eskandari Deal',
    title: 'Immigration Attorney',
    firm: 'Levine & Eskandari LC',
    location: 'Atlanta, GA',
    address: '280 Interstate North Circle SE Suite 450, Atlanta, GA 30339',
    phones: [{ label: 'Office', number: '770-551-2700' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'ldeal@leimmigration.com',
  },
  {
    id: 90,
    name: 'Jeremy Smith',
    title: 'Immigration Attorney',
    firm: 'Smith Immigration Law Office, P.C.',
    location: 'Buford, GA',
    address: 'P.O. Box 1388, Buford, GA 30515',
    phones: [{ label: 'Office', number: '678-200-2910' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'jeremy@abogadojeremias.com',
  },
  {
    id: 91,
    name: 'Charles Keith Wood Jr.',
    title: 'Immigration Attorney',
    firm: 'Law Office of C. Keith Wood, Jr.',
    location: 'Jonesboro, GA',
    address: '7745 Jonesboro Rd., Jonesboro, GA 30236',
    phones: [{ label: 'Office', number: '770-471-4282' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 92,
    name: 'Jameel Manji',
    title: 'Immigration Attorney',
    firm: 'Manji Law PC',
    location: 'Tucker, GA',
    address: '5745 Lawrenceville Hwy, Tucker, GA 30084',
    phones: [{ label: 'Office', number: '678-902-2999' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 93,
    name: 'Hilary Smith',
    title: 'Immigration Attorney',
    firm: 'Law Offices of Hilary Smith, LLC',
    location: 'Marietta, GA',
    address: '80 Whitlock Place SW Suite 101, Marietta, GA 30064',
    phones: [{ label: 'Office', number: '404-418-8989' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 94,
    name: 'Stacy M Ehrisman',
    title: 'Immigration Attorney',
    firm: 'The Ehrisman Law Firm, P.C.',
    location: 'Lawrenceville, GA',
    address: '572 Buford Drive, Lawrenceville, GA 30046',
    phones: [{ label: 'Office', number: '678-985-0313' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'stacy@ehrismanlaw.com',
  },
  // ── Arizona ──────────────────────────────────────────────────────────────────
  {
    id: 95,
    name: 'Pamela Florian',
    title: 'Immigration Attorney',
    firm: 'Acceso Immigration Law, PLLC',
    location: 'Tucson, AZ',
    address: '2030 E Broadway Blvd Ste 102, Tucson, AZ 85719',
    phones: [{ label: 'Office', number: '520-789-4360' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 96,
    name: 'Juan Rocha',
    title: 'Immigration Attorney',
    firm: 'Rocha Law Office',
    location: 'Mesa, AZ',
    address: 'P.O. Box 5965, Mesa, AZ 85211',
    phones: [{ label: 'Office', number: '480-855-1759' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'juanrocha@jrochalaw.com',
  },
  {
    id: 97,
    name: 'Emma D. Wells',
    title: 'Immigration Attorney',
    firm: 'Law Office of Emma D. Wells, PLLC',
    location: 'Peoria, AZ',
    address: '24654 N. Lake Pleasant Pkwy Suite 103-289, Peoria, AZ 85383',
    phones: [{ label: 'Office', number: '602-622-9680' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 98,
    name: 'Timothy A. Gambacorta',
    title: 'Immigration Attorney',
    firm: 'The Gambacorta Law Office, LLC',
    location: 'Phoenix, AZ',
    address: '1 East Washington Street Suite 500, Phoenix, AZ 85004',
    phones: [{ label: 'Office', number: '602-325-8002' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'tim@gambacortalaw.com',
  },
  {
    id: 99,
    name: 'Matthew H. Green',
    title: 'Immigration Attorney',
    firm: 'Green Evans-Schroeder',
    location: 'Tucson, AZ',
    address: '130 W. Cushing Street, Tucson, AZ 85701',
    phones: [{ label: 'Office', number: '520-882-8852' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 100,
    name: 'Daniel Peter Lubarsky-Ford',
    title: 'Immigration Attorney',
    firm: 'Lubarsky Ford PLLC',
    location: 'Tempe, AZ',
    address: '424 E. Southern Ave. Suite 102, Tempe, AZ 85282',
    phones: [{ label: 'Office', number: '602-300-6183' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 101,
    name: 'Rachel Bus',
    title: 'Immigration Attorney',
    firm: 'Law Offices of Brelje and Associates',
    location: 'Goodyear, AZ',
    address: '3080 N. Litchfield Rd., Goodyear, AZ 85395',
    phones: [{ label: 'Office', number: '623-536-5750' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'breljeinfo@breljelaw.com',
  },
  {
    id: 102,
    name: 'Jared C. Leung',
    title: 'Immigration Attorney',
    firm: 'JCL Immigration Attorneys, PLLC',
    location: 'Scottsdale, AZ',
    address: '1375 N Scottsdale Road Suite 390, Scottsdale, AZ 85257',
    phones: [{ label: 'Office', number: '602-831-2329' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'info@jclimmigration.com',
  },
  // ── Tennessee ────────────────────────────────────────────────────────────────
  {
    id: 103,
    name: 'Kara L. Youngblood',
    title: 'Immigration Attorney',
    firm: 'Youngblood & Associates, PLLC',
    location: 'McMinnville, TN',
    address: '118 N. Spring Street, McMinnville, TN 37110',
    phones: [{ label: 'Office', number: '931-274-7811' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 104,
    name: 'Terrence Lee Olsen',
    title: 'Immigration Attorney',
    firm: 'Law Office of Terrence Lee Olsen',
    location: 'Chattanooga, TN',
    address: '615 Lindsay St. Suite 330, Chattanooga, TN 37403',
    phones: [{ label: 'Office', number: '423-648-9390' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 105,
    name: 'Elizabeth Patton',
    title: 'Immigration Attorney',
    firm: 'Rose Immigration Law Firm, PLC',
    location: 'Brentwood, TN',
    address: '105 Westpark Drive Suite 330, Brentwood, TN 37027',
    phones: [{ label: 'Office', number: '615-321-2256' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'epatton@roseimmigration.com',
  },
  {
    id: 106,
    name: 'Casey Bryant',
    title: 'Immigration Attorney',
    firm: 'Advocates for Immigrant Rights',
    location: 'Memphis, TN',
    address: '815 N. McLean Blvd, Memphis, TN 38174',
    phones: [{ label: 'Office', number: '901-729-9566' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: 'casey@airlegal.org',
  },
  {
    id: 107,
    name: 'Michael A. Eastridge',
    title: 'Immigration Attorney',
    firm: 'Hunter, Smith & Davis, LLP',
    location: 'Kingsport, TN',
    address: '1212 N. Eastman Rd., Kingsport, TN 37664',
    phones: [{ label: 'Office', number: '423-378-8800' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 108,
    name: 'Corey Austin Spearman',
    title: 'Immigration Attorney',
    firm: 'Nación del Inmigrante',
    location: 'Tullahoma, TN',
    address: '111 NW Atlantic St Ste 200, Tullahoma, TN 37388',
    phones: [{ label: 'Office', number: '931-563-0808' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 109,
    name: 'Sandra Susana Gibbs',
    title: 'Immigration Attorney',
    firm: 'Sandra Gibbs Law, Inc.',
    location: 'Lebanon, TN',
    address: '115 E Main Street Ste. F, Lebanon, TN 37088',
    phones: [{ label: 'Office', number: '615-810-8186' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
  {
    id: 110,
    name: 'Martin W. Lester',
    title: 'Immigration Attorney',
    firm: 'Lester Law',
    location: 'Hixson, TN',
    address: 'P.O. Box 968, Hixson, TN 37343',
    phones: [{ label: 'Office', number: '423-402-0608' }],
    hours: null,
    specialties: [],
    languages: null,
    canadian: null,
    bio: null,
    note: null,
    badge: null,
    category: 'Attorneys',
    stars: null,
    reviews: null,
    expanded: false,
    primaryAction: 'Request Introduction',
    has_account: false,
    email: null,
  },
]

function TabBar({ active }) {
  const navigate = useNavigate()
  return (
    <div
      className="fixed bottom-0 left-0 right-0 z-40 flex overflow-x-auto"
      style={{ backgroundColor: '#0D2B4E', borderTop: '1px solid rgba(255,255,255,0.1)', scrollbarWidth: 'none' }}
    >
      {TABS.map((tab) => {
        const isActive = tab.id === active
        return (
          <button key={tab.id} onClick={() => navigate(tab.path)}
            className="flex-shrink-0 flex flex-col items-center justify-center px-3 py-2.5 gap-0.5"
            style={{ minWidth: 64 }}
          >
            <span className="text-xs font-semibold whitespace-nowrap"
              style={{ color: isActive ? '#F0A500' : 'rgba(255,255,255,0.5)' }}>
              {tab.label}
            </span>
            {isActive && <div className="w-4 h-0.5 rounded-full" style={{ backgroundColor: '#F0A500' }} />}
          </button>
        )
      })}
    </div>
  )
}

function Stars({ count }) {
  return (
    <div className="flex gap-0.5">
      {[1, 2, 3, 4, 5].map((i) => (
        <svg key={i} width="13" height="13" viewBox="0 0 24 24"
          fill={i <= count ? '#F0A500' : '#E2E8F0'} stroke="none">
          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
        </svg>
      ))}
    </div>
  )
}

function SpecialtyPill({ label }) {
  return (
    <span
      className="text-xs font-semibold px-2.5 py-1 rounded-full"
      style={{ backgroundColor: '#EBF4FB', color: '#1B5FA8' }}
    >
      {label}
    </span>
  )
}

function ProfessionalCard({ pro, initialOpen, presignup, presignupVisa, presignupDest }) {
  const navigate = useNavigate()
  const [open, setOpen] = useState(initialOpen)
  const [requested, setRequested] = useState(false)
  const [requesting, setRequesting] = useState(false)

  function handlePresignupSelect() {
    try {
      localStorage.setItem('migratrak_selected_attorney', pro.has_account ? (pro.supabase_id || '') : '')
    } catch {}
    navigate('/auth', {
      state: { mode: 'signup', visa_type: presignupVisa || '', destination_state: presignupDest || '' }
    })
  }

  async function handleRequest() {
    if (requested || requesting) return
    setRequesting(true)

    try {
      // Always store the selection in localStorage for D-flow pre-signup path
      try {
        localStorage.setItem('migratrak_selected_attorney', pro.has_account ? (pro.supabase_id || '') : '')
      } catch {}

      // Check if user is currently logged in
      const { data: { user } } = await supabase.auth.getUser()

      if (user) {
        // Fetch user profile for prospect data
        const { data: profile } = await supabase.from('users').select('name, email, visa_type, role').eq('id', user.id).single()

        if (pro.has_account && pro.supabase_id) {
          // Attorney has a MigraTrak account — create prospect record linked to them
          const answers = (() => { try { return JSON.parse(localStorage.getItem('migratrak_answers') || '{}') } catch { return {} } })()
          await fetch('/api/score-prospect', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              name: profile?.name || user.email,
              email: profile?.email || user.email,
              visa_type: profile?.visa_type || answers.visa_type || null,
              budget_range: answers.budget || null,
              destination_state: null,
              assessment_answers: answers,
              attorney_id: pro.supabase_id,
            }),
          })
        } else {
          // Professional has no MigraTrak account — send intro email to hello@migratrak.app
          const answers = (() => { try { return JSON.parse(localStorage.getItem('migratrak_answers') || '{}') } catch { return {} } })()
          await fetch('/api/request-intro', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              prospect_name: profile?.name || user.email,
              prospect_email: profile?.email || user.email,
              visa_type: profile?.visa_type || null,
              budget_range: answers.budget || null,
              ai_note: null,
              professional_name: pro.name,
              professional_firm: pro.firm || null,
              professional_category: pro.category || null,
            }),
          })
        }
      }
      // If not logged in: localStorage already set above — handled by score-prospect after signup
      setRequested(true)
    } catch {
      // Still mark as requested even if backend fails — don't block the user
      setRequested(true)
    } finally {
      setRequesting(false)
    }
  }

  return (
    <div
      className="rounded-2xl overflow-hidden shadow-sm"
      style={{
        backgroundColor: '#FFFFFF',
        border: '1px solid #E2E8F0',
      }}
    >
      {/* Card header — always visible */}
      <button
        onClick={() => setOpen(!open)}
        className="w-full text-left px-5 py-4 transition-opacity active:opacity-70"
      >
        <div className="flex items-start justify-between gap-2">
          <div className="flex items-start gap-3">
            {/* Avatar */}
            <div
              className="w-12 h-12 rounded-2xl flex items-center justify-center flex-shrink-0 text-xl font-bold"
              style={{ backgroundColor: '#EBF4FB', color: '#1B5FA8' }}
            >
              {pro.name.charAt(0)}
            </div>
            <div>
              <div className="flex items-center gap-2 flex-wrap">
                <p className="text-base font-extrabold leading-tight" style={{ color: '#0D2B4E' }}>
                  {pro.name}
                </p>
              </div>
              <p className="text-xs mt-0.5" style={{ color: '#4A5568' }}>
                {pro.title}{pro.firm ? ` · ${pro.firm}` : ''}
              </p>
              {pro.location && (
                <p className="text-xs mt-0.5" style={{ color: '#4A9FD4' }}>
                  📍 {pro.location}
                </p>
              )}
              {pro.reviews && (
                <div className="flex items-center gap-1.5 mt-1">
                  <Stars count={pro.stars} />
                  <span className="text-xs" style={{ color: '#4A5568' }}>
                    {pro.reviews} verified reviews
                  </span>
                </div>
              )}
              {!pro.reviews && (
                <div className="mt-1"><Stars count={pro.stars} /></div>
              )}
            </div>
          </div>
          <svg
            width="18" height="18" viewBox="0 0 24 24" fill="none"
            stroke="#A0AEC0" strokeWidth="2.5" strokeLinecap="round" className="flex-shrink-0 mt-1"
            style={{ transform: open ? 'rotate(180deg)' : 'rotate(0deg)', transition: 'transform 0.2s' }}
          >
            <path d="M6 9l6 6 6-6" />
          </svg>
        </div>

        {/* Specialty pills — always visible */}
        <div className="flex flex-wrap gap-1.5 mt-3">
          {pro.specialties.map((s) => <SpecialtyPill key={s} label={s} />)}
        </div>
      </button>

      {/* Expanded detail */}
      {open && (
        <div className="px-5 pb-5 flex flex-col gap-4" style={{ borderTop: '1px solid #F1F5F9' }}>

          {/* Bio */}
          {pro.bio && (
            <p className="text-sm leading-relaxed pt-3 italic" style={{ color: '#4A5568' }}>
              "{pro.bio}"
            </p>
          )}

          {/* Note */}
          {pro.note && (
            <div className="rounded-xl px-3 py-2.5" style={{ backgroundColor: '#FFFBEB', border: '1px solid #FCD34D' }}>
              <p className="text-xs leading-relaxed" style={{ color: '#78350F' }}>{pro.note}</p>
            </div>
          )}

          {/* Accepting new patients */}
          {pro.accepting && (
            <p className="text-xs font-semibold" style={{ color: '#1A7A4A' }}>✓ Accepting new patients</p>
          )}

          {/* Details grid */}
          <div className="flex flex-col gap-2">
            {pro.address && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Address</span>
                <p className="text-sm whitespace-pre-line" style={{ color: '#0D2B4E' }}>{pro.address}</p>
              </div>
            )}
            {pro.id === 1 && pro.phones.length > 0 && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Phone</span>
                <div className="flex flex-col gap-0.5">
                  {pro.phones.map((p) => (
                    <a key={p.label} href={`tel:${p.number.replace(/\D/g,'')}`}
                      className="text-sm font-semibold" style={{ color: '#1B5FA8' }}>
                      {p.label}: {p.number}
                    </a>
                  ))}
                </div>
              </div>
            )}
            {pro.id !== 1 && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Phone</span>
                <p className="text-sm" style={{ color: '#94A3B8' }}>Coming soon</p>
              </div>
            )}
            {pro.id !== 1 && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Email</span>
                <p className="text-sm" style={{ color: '#94A3B8' }}>Coming soon</p>
              </div>
            )}
            {pro.hours && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Hours</span>
                <p className="text-sm" style={{ color: '#0D2B4E' }}>{pro.hours}</p>
              </div>
            )}
            {pro.languages && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Languages</span>
                <p className="text-sm" style={{ color: '#0D2B4E' }}>{pro.languages.join(', ')}</p>
              </div>
            )}
            {pro.canadian && (
              <div className="flex gap-2">
                <span className="text-xs font-extrabold uppercase tracking-wider w-20 flex-shrink-0 pt-0.5" style={{ color: '#4A5568' }}>Canadian</span>
                <p className="text-sm" style={{ color: '#1A7A4A' }}>🍁 {pro.canadian}</p>
              </div>
            )}
          </div>

          {/* Action buttons */}
          <div className="flex flex-col gap-2 pt-1">
            {/* Call Now (Mena only) + Request Introduction */}
            <div className="flex gap-2">
              {pro.id === 1 && pro.phones.length > 0 && (
                <a
                  href={`tel:${pro.phones[0].number.replace(/\D/g,'')}`}
                  className="flex-1 py-2.5 rounded-xl text-sm font-bold text-center transition-all active:scale-95"
                  style={{ backgroundColor: '#1A7A4A', color: '#FFFFFF' }}
                >
                  📞 Call Now
                </a>
              )}
            </div>
            {/* Primary action */}
            {presignup ? (
              <button
                onClick={handlePresignupSelect}
                className="w-full py-3 rounded-xl text-sm font-bold transition-all active:scale-95"
                style={{ backgroundColor: '#F0A500', color: '#0D2B4E' }}
              >
                Select this attorney →
              </button>
            ) : (
              <button
                onClick={handleRequest}
                disabled={requesting}
                className="w-full py-3 rounded-xl text-sm font-bold transition-all active:scale-95"
                style={{
                  backgroundColor: requested ? '#D1FAE5' : '#F0A500',
                  color: requested ? '#1A7A4A' : '#0D2B4E',
                  opacity: requesting ? 0.7 : 1,
                }}
              >
                {requesting ? 'Sending…' : requested ? `✓ ${pro.primaryAction || 'Request Introduction'} confirmed` : `${pro.primaryAction || 'Request Introduction'} →`}
              </button>
            )}
          </div>
        </div>
      )}

      {/* Collapsed action strip */}
      {!open && (
        <div className="flex gap-2 px-5 pb-4">
          {presignup ? (
            <button
              onClick={handlePresignupSelect}
              className="flex-1 py-2 rounded-xl text-xs font-bold transition-all active:scale-95"
              style={{ backgroundColor: '#F0A500', color: '#0D2B4E' }}
            >
              Select this attorney →
            </button>
          ) : (
            <button
              onClick={handleRequest}
              disabled={requesting}
              className="flex-1 py-2 rounded-xl text-xs font-bold transition-all active:scale-95"
              style={{
                backgroundColor: requested ? '#D1FAE5' : '#F0A500',
                color: requested ? '#1A7A4A' : '#0D2B4E',
                opacity: requesting ? 0.7 : 1,
              }}
            >
              {requesting ? '…' : requested ? '✓ Done' : (pro.primaryAction || 'Request Intro') + ' →'}
            </button>
          )}
        </div>
      )}
    </div>
  )
}

export default function J5Directory() {
  const { state } = useLocation()
  const presignup = state?.presignup === true
  const presignupVisa = state?.visa_type || ''
  const presignupDest = state?.destination_state || ''

  const filterMap = { attorneys: 'Attorneys', cpas: 'CPAs', 'financial-advisors': 'Financial Advisors', healthcare: 'Healthcare', 'vehicle-import': 'Vehicle Import' }
  const initialFilter = presignup ? 'Attorneys' : (filterMap[state?.filter] ?? 'All')
  const [activeFilter, setActiveFilter] = useState(initialFilter)

  const filtered = activeFilter === 'All'
    ? PROFESSIONALS
    : PROFESSIONALS.filter((p) => p.category === activeFilter)

  return (
    <div className="min-h-screen flex flex-col" style={{ backgroundColor: '#F7F9FC' }}>

      {/* Header */}
      <div className="px-5 pt-5 pb-4" style={{ backgroundColor: '#0D2B4E' }}>
        <p className="text-xs font-semibold uppercase tracking-widest mb-1" style={{ color: '#4A9FD4' }}>
          {presignup ? 'Step 1 of 2' : 'Professional Directory'}
        </p>
        <h1 className="text-2xl font-extrabold" style={{ color: '#FFFFFF' }}>
          {presignup ? 'Choose your immigration specialist' : 'Find the Right Professional'}
        </h1>
        <p className="text-sm mt-1" style={{ color: 'rgba(255,255,255,0.6)' }}>
          {presignup ? 'Select a specialist below — we\'ll connect you after you create your account.' : 'Vetted specialists who understand the Canadian to US journey'}
        </p>
      </div>

      {/* Pre-signup banner */}
      {presignup && (
        <div className="px-4 py-3" style={{ backgroundColor: '#EBF4FB', borderBottom: '1px solid #4A9FD4' }}>
          <p className="text-xs font-semibold" style={{ color: '#1B5FA8' }}>
            Tap "Select this attorney" on any card below, then we'll take you straight to account creation.
          </p>
        </div>
      )}

      {/* Filter bar */}
      <div
        className="flex gap-2 px-4 py-3 overflow-x-auto sticky top-0 z-30"
        style={{ backgroundColor: '#F7F9FC', borderBottom: '1px solid #E2E8F0', scrollbarWidth: 'none' }}
      >
        {FILTERS.map((f) => {
          const isActive = f === activeFilter
          return (
            <button
              key={f}
              onClick={() => setActiveFilter(f)}
              className="flex-shrink-0 px-4 py-2 rounded-full text-xs font-bold transition-all active:scale-95"
              style={{
                backgroundColor: isActive ? '#0D2B4E' : '#FFFFFF',
                color: isActive ? '#F0A500' : '#4A5568',
                border: isActive ? '2px solid #0D2B4E' : '2px solid #E2E8F0',
              }}
            >
              {f}
            </button>
          )
        })}
      </div>

      {/* Directory disclaimer */}
      <div className="px-4 py-2.5" style={{ borderBottom: '1px solid #F1F5F9' }}>
        <p className="text-xs leading-relaxed" style={{ color: '#94A3B8' }}>
          Directory listings are for informational purposes only. MigraTrak does not endorse or guarantee the services of any listed professional. Always verify credentials independently.
        </p>
      </div>

      {/* Cards */}
      <div className="flex flex-col gap-4 px-4 pt-4 pb-40">
        {filtered.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <p className="text-base font-semibold" style={{ color: '#4A5568' }}>
              No listings in this category yet
            </p>
            <p className="text-sm mt-1" style={{ color: '#A0AEC0' }}>
              Check back soon — we're adding specialists weekly
            </p>
          </div>
        ) : (
          filtered.map((pro) => (
            <ProfessionalCard
              key={pro.id}
              pro={pro}
              initialOpen={pro.expanded}
              presignup={presignup}
              presignupVisa={presignupVisa}
              presignupDest={presignupDest}
            />
          ))
        )}

        {/* Footer note */}
        <div
          className="rounded-2xl px-4 py-4 text-center"
          style={{ backgroundColor: '#EBF4FB', border: '1px solid #4A9FD4' }}
        >
          <p className="text-xs leading-relaxed" style={{ color: '#0D2B4E' }}>
            All professionals listed have been reviewed by the MigraTrak team. MigraTrak may receive a referral fee. This does not affect the quality or independence of our recommendations.
          </p>
        </div>
      </div>

      <TabBar active="directory" />
    </div>
  )
}
